In [254]:
import pandas as pd
import numpy as np
import torch
import torch.nn.functional as F
import torch.nn as nn

In [255]:
class FFNN(nn.Module):

    def __init__(self, h_size: int, out_n: int, drop: float=None):
        super().__init__()
        self.l1 = nn.Linear(42,h_size)
        self.l2 = nn.Linear(h_size, h_size)
        self.l3 = nn.Linear(h_size, h_size // 2)
        self.l4 = nn.Linear(h_size // 2, out_n)
        if drop:
            self.d1 = nn.Dropout(drop)
            self.d2 = nn.Dropout(drop)
        else:
            self.d1 = self.d2 = None
    
    def forward(self, X):
        """
        Forward pass of the neural network
        """
        X = F.relu(self.l1(X))
        X = F.relu(self.l2(X))
        if self.d1:
            X = self.d1(X)
        X = F.relu(self.l3(X))
        if self.d2:
            X = self.d2(X)
        X = F.relu(self.l4(X))
        # return F.softmax(X)
        return X

In [256]:
device = 'cuda'

In [257]:
import os
os.getcwd()

'c:\\Users\\Lucas\\OneDrive\\A Level\\Computer Science Code\\Hand Detection NEA\\Real Thing\\repo'

In [258]:
data = pd.read_csv('c:\\Users\\Lucas\\OneDrive\\A Level\\Computer Science Code\\Hand Detection NEA\\Real Thing\\data.csv')
cols = data.columns
print(cols)
data = data.sample(frac=1)

Index(['label', 'hand', 'data0', 'data1', 'data2', 'data3', 'data4', 'data5',
       'data6', 'data7', 'data8', 'data9', 'data10', 'data11', 'data12',
       'data13', 'data14', 'data15', 'data16', 'data17', 'data18', 'data19',
       'data20', 'data21', 'data22', 'data23', 'data24', 'data25', 'data26',
       'data27', 'data28', 'data29', 'data30', 'data31', 'data32', 'data33',
       'data34', 'data35', 'data36', 'data37', 'data38', 'data39', 'data40',
       'data41'],
      dtype='object')

In [259]:
Y_col = cols[0]
X_col = cols[2:]

In [260]:
X, Y = data[X_col], data[[Y_col]]

In [261]:
X

,data0,data1,data2,data3,data4,data5,data6,data7,data8,data9,...,data32,data33,data34,data35,data36,data37,data38,data39,data40,data41
909,0.284153,1.000000,0.524590,0.930233,0.754098,0.573643,0.890710,0.286822,1.000000,0.131783,...,0.185792,0.759690,0.043716,0.248062,0.049180,0.217054,0.021858,0.534884,0.000000,0.697674
898,0.160870,1.000000,0.469565,0.911458,0.726087,0.552083,0.869565,0.239583,1.000000,0.015625,...,0.269565,0.395833,0.000000,0.151042,0.104348,0.093750,0.134783,0.348958,0.095652,0.385417
2845,0.197411,1.000000,0.433657,0.945238,0.647249,0.819048,0.838188,0.716667,1.000000,0.654762,...,0.262136,0.769048,0.000000,0.621429,0.042071,0.604762,0.100324,0.726190,0.126214,0.759524
167,0.567376,1.000000,0.893617,0.880102,1.000000,0.693878,0.872340,0.525510,0.673759,0.397959,...,0.460993,0.673469,0.056738,0.645408,0.000000,0.573980,0.170213,0.681122,0.234043,0.719388
1192,1.000000,1.000000,0.660256,0.728324,0.467949,0.419075,0.397436,0.190751,0.480769,0.000000,...,0.467949,0.760116,0.929487,0.849711,0.256410,0.858382,0.365385,0.887283,0.589744,0.893064
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1333,0.047619,0.813665,0.303571,0.611801,0.523810,0.357143,0.589286,0.167702,0.559524,0.000000,...,0.369048,0.816770,0.000000,0.931677,0.595238,0.987578,0.476190,1.000000,0.250000,0.959627
1766,0.805310,1.000000,0.491150,0.921397,0.287611,0.768559,0.283186,0.628821,0.407080,0.513100,...,0.477876,0.733624,1.000000,0.648472,0.725664,0.644105,0.606195,0.744541,0.597345,0.814410
3369,0.058594,1.000000,0.363281,0.958656,0.648438,0.819121,0.820312,0.687339,1.000000,0.596899,...,0.199219,0.744186,0.003906,0.604651,0.000000,0.534884,0.039062,0.648579,0.074219,0.726098
2662,0.569536,1.000000,0.390728,0.865248,0.274834,0.661939,0.142384,0.484634,0.000000,0.368794,...,0.658940,0.725768,0.960265,0.699764,1.000000,0.683215,0.844371,0.777778,0.768212,0.784870
942,0.000000,1.000000,0.356784,0.956731,0.673367,0.649038,0.834171,0.312500,1.000000,0.076923,...,0.256281,0.442308,0.075377,0.250000,0.115578,0.125000,0.075377,0.355769,0.080402,0.442308

In [262]:
Y

      label
909       1
898       1
2845      5
167       0
1192      2
...     ...
1333      2
1766      3
3369      6
2662      5
942       1

[3582 rows x 1 columns]

In [263]:
Y.value_counts()

label
2        527
0        519
4        515
5        508
3        507
1        503
6        503
Name: count, dtype: int64

In [264]:
l = len(X)
split = (0.8 * l).__floor__()
print(split)

2865

In [265]:
X_train, X_test = X[:split], X[split:]
Y_train, Y_test = Y[:split], Y[split:]

In [266]:
print(X_test)

         data0     data1     data2     data3     data4     data5     data6  \
2660  0.587248  1.000000  0.399329  0.871981  0.281879  0.669082  0.154362
355   0.585366  1.000000  0.231707  0.880407  0.060976  0.674300  0.073171
315   0.790514  1.000000  0.505929  0.860412  0.316206  0.643021  0.237154
959   0.045267  1.000000  0.374486  0.986239  0.699588  0.619266  0.872428
1044  1.000000  0.909657  0.876404  0.644860  0.632959  0.395639  0.426966
...        ...       ...       ...       ...       ...       ...       ...
1333  0.047619  0.813665  0.303571  0.611801  0.523810  0.357143  0.589286
1766  0.805310  1.000000  0.491150  0.921397  0.287611  0.768559  0.283186
3369  0.058594  1.000000  0.363281  0.958656  0.648438  0.819121  0.820312
2662  0.569536  1.000000  0.390728  0.865248  0.274834  0.661939  0.142384
942   0.000000  1.000000  0.356784  0.956731  0.673367  0.649038  0.834171

         data7     data8     data9  ...    data32    data33    data34  \
2660  0.495169  0.000000  0.381643  ...  0.651007  0.746377  0.969799
355   0.501272  0.054878  0.366412  ...  0.493902  0.796438  1.000000
315   0.471396  0.177866  0.334096  ...  0.600791  0.748284  1.000000
959   0.279817  1.000000  0.064220  ...  0.238683  0.463303  0.000000
1044  0.193146  0.344569  0.000000  ...  0.198502  0.878505  0.565543
...        ...       ...       ...  ...       ...       ...       ...
1333  0.167702  0.559524  0.000000  ...  0.369048  0.816770  0.000000
1766  0.628821  0.407080  0.513100  ...  0.477876  0.733624  1.000000
3369  0.687339  1.000000  0.596899  ...  0.199219  0.744186  0.003906
2662  0.484634  0.000000  0.368794  ...  0.658940  0.725768  0.960265
942   0.312500  1.000000  0.076923  ...  0.256281  0.442308  0.075377

        data35    data36    data37    data38    data39    data40    data41
2660  0.698068  1.000000  0.669082  0.848993  0.772947  0.775168  0.792271
355   0.620865  0.829268  0.562341  0.701220  0.687023  0.707317  0.763359
315   0.562929  0.778656  0.528604  0.687747  0.645309  0.691700  0.723112
959   0.211009  0.119342  0.169725  0.111111  0.454128  0.057613  0.472477
1044  1.000000  0.176030  0.987539  0.209738  0.990654  0.314607  0.996885
...        ...       ...       ...       ...       ...       ...       ...
1333  0.931677  0.595238  0.987578  0.476190  1.000000  0.250000  0.959627
1766  0.648472  0.725664  0.644105  0.606195  0.744541  0.597345  0.814410
3369  0.604651  0.000000  0.534884  0.039062  0.648579  0.074219  0.726098
2662  0.699764  1.000000  0.683215  0.844371  0.777778  0.768212  0.784870
942   0.250000  0.115578  0.125000  0.075377  0.355769  0.080402  0.442308

[717 rows x 42 columns]

In [267]:
ffnn = FFNN(128, 7, 0.5)
loss_fn = nn.CrossEntropyLoss()
ffnn = ffnn.to(device)
loss_fn = loss_fn.to(device)

X_train = torch.tensor(X_train.to_numpy(), dtype=torch.float).to(device)
X_test = torch.tensor(X_test.to_numpy(), dtype=torch.float).to(device)
Y_train = torch.tensor(Y_train.to_numpy(), dtype=torch.int64).reshape(-1).to(device)
Y_test = torch.tensor(Y_test.to_numpy(), dtype=torch.int64).reshape(-1).to(device)

optim = torch.optim.Adam(ffnn.parameters())

epochs = 301

for epoch in range(1, epochs):
    optim.zero_grad()

    Y_hat = ffnn(X_train)

    loss = loss_fn(Y_hat, Y_train)
    accuracy = torch.mean((torch.argmax(Y_hat, dim=1) == Y_train).float()).float()

    print(f'Epoch: {epoch}, Accuracy: {accuracy}, Loss: {loss.item()}')

    loss.backward()
    optim.step()

Y_test_hat = ffnn(X_test)
accuracy = torch.mean((torch.argmax(Y_test_hat, dim=1) == Y_test).float()).float()
print(f'Testing accuracy: {accuracy}')
torch.save(ffnn.state_dict(), '.\\model.pickle')

Epoch: 1, Accuracy: 0.13089005649089813, Loss: 1.950463891029358
Epoch: 2, Accuracy: 0.1357766091823578, Loss: 1.9473222494125366
Epoch: 3, Accuracy: 0.14624781906604767, Loss: 1.9447627067565918
Epoch: 4, Accuracy: 0.1518324613571167, Loss: 1.9434430599212646
Epoch: 5, Accuracy: 0.17102967202663422, Loss: 1.940143346786499
Epoch: 6, Accuracy: 0.19825479388237, Loss: 1.9364290237426758
Epoch: 7, Accuracy: 0.21361257135868073, Loss: 1.9340406656265259
Epoch: 8, Accuracy: 0.23350785672664642, Loss: 1.929067611694336
Epoch: 9, Accuracy: 0.27260035276412964, Loss: 1.9229764938354492
Epoch: 10, Accuracy: 0.2712042033672333, Loss: 1.9195791482925415
Epoch: 11, Accuracy: 0.2938917875289917, Loss: 1.9114437103271484
Epoch: 12, Accuracy: 0.31832462549209595, Loss: 1.9049228429794312
Epoch: 13, Accuracy: 0.320069819688797, Loss: 1.89642333984375
Epoch: 14, Accuracy: 0.31797558069229126, Loss: 1.8891289234161377
Epoch: 15, Accuracy: 0.35811519622802734, Loss: 1.8782941102981567
Epoch: 16, Accuracy: 0.37137871980667114, Loss: 1.8662748336791992
Epoch: 17, Accuracy: 0.36055848002433777, Loss: 1.8578832149505615
Epoch: 18, Accuracy: 0.3832460641860962, Loss: 1.8415417671203613
Epoch: 19, Accuracy: 0.3724258244037628, Loss: 1.8326852321624756
Epoch: 20, Accuracy: 0.3853403329849243, Loss: 1.8159326314926147
Epoch: 21, Accuracy: 0.39092496037483215, Loss: 1.7965587377548218
Epoch: 22, Accuracy: 0.41116929054260254, Loss: 1.7735607624053955
Epoch: 23, Accuracy: 0.41082024574279785, Loss: 1.751254677772522
Epoch: 24, Accuracy: 0.41082024574279785, Loss: 1.7407302856445312
Epoch: 25, Accuracy: 0.4157068133354187, Loss: 1.7085741758346558
Epoch: 26, Accuracy: 0.4251309037208557, Loss: 1.6856334209442139
Epoch: 27, Accuracy: 0.4390924870967865, Loss: 1.659824252128601
Epoch: 28, Accuracy: 0.44432809948921204, Loss: 1.6283857822418213
Epoch: 29, Accuracy: 0.4429319500923157, Loss: 1.5993884801864624
Epoch: 30, Accuracy: 0.4394415318965912, Loss: 1.5757997035980225
Epoch: 31, Accuracy: 0.4544502794742584, Loss: 1.5435161590576172
Epoch: 32, Accuracy: 0.4684118628501892, Loss: 1.5117233991622925
Epoch: 33, Accuracy: 0.4876090884208679, Loss: 1.4702014923095703
Epoch: 34, Accuracy: 0.49982547760009766, Loss: 1.4435229301452637
Epoch: 35, Accuracy: 0.5106457471847534, Loss: 1.4057668447494507
Epoch: 36, Accuracy: 0.527748703956604, Loss: 1.3723140954971313
Epoch: 37, Accuracy: 0.5312390923500061, Loss: 1.340686559677124
Epoch: 38, Accuracy: 0.5462478399276733, Loss: 1.3035279512405396
Epoch: 39, Accuracy: 0.5664921402931213, Loss: 1.2640146017074585
Epoch: 40, Accuracy: 0.5891797542572021, Loss: 1.2221146821975708
Epoch: 41, Accuracy: 0.5923210978507996, Loss: 1.1941834688186646
Epoch: 42, Accuracy: 0.596509575843811, Loss: 1.1698025465011597
Epoch: 43, Accuracy: 0.612914502620697, Loss: 1.1289856433868408
Epoch: 44, Accuracy: 0.623734712600708, Loss: 1.0959399938583374
Epoch: 45, Accuracy: 0.6230366826057434, Loss: 1.0802041292190552
Epoch: 46, Accuracy: 0.6272251605987549, Loss: 1.043738842010498
Epoch: 47, Accuracy: 0.6474694609642029, Loss: 1.0008214712142944
Epoch: 48, Accuracy: 0.6551483273506165, Loss: 0.9677072167396545
Epoch: 49, Accuracy: 0.6541012525558472, Loss: 0.9458528757095337
Epoch: 50, Accuracy: 0.6499127745628357, Loss: 0.937360405921936
Epoch: 51, Accuracy: 0.6663176417350769, Loss: 0.8921027779579163
Epoch: 52, Accuracy: 0.6527050733566284, Loss: 0.8951776027679443
Epoch: 53, Accuracy: 0.6750436425209045, Loss: 0.8606282472610474
Epoch: 54, Accuracy: 0.6778359413146973, Loss: 0.853972315788269
Epoch: 55, Accuracy: 0.6890052556991577, Loss: 0.8120301365852356
Epoch: 56, Accuracy: 0.6834205985069275, Loss: 0.813858151435852
Epoch: 57, Accuracy: 0.6984293460845947, Loss: 0.7924869656562805
Epoch: 58, Accuracy: 0.6788830757141113, Loss: 0.8008503317832947
Epoch: 59, Accuracy: 0.6879581212997437, Loss: 0.7798771858215332
Epoch: 60, Accuracy: 0.6914485096931458, Loss: 0.768623948097229
Epoch: 61, Accuracy: 0.7026178240776062, Loss: 0.7504273653030396
Epoch: 62, Accuracy: 0.6963350772857666, Loss: 0.7290468811988831
Epoch: 63, Accuracy: 0.706457257270813, Loss: 0.733288586139679
Epoch: 64, Accuracy: 0.706457257270813, Loss: 0.727604329586029
Epoch: 65, Accuracy: 0.6991274356842041, Loss: 0.7200000882148743
Epoch: 66, Accuracy: 0.7036648988723755, Loss: 0.6977138519287109
Epoch: 67, Accuracy: 0.7207679152488708, Loss: 0.6958774924278259
Epoch: 68, Accuracy: 0.7106457352638245, Loss: 0.6900525689125061
Epoch: 69, Accuracy: 0.7301920056343079, Loss: 0.6632115244865417
Epoch: 70, Accuracy: 0.7280977368354797, Loss: 0.6704040765762329
Epoch: 71, Accuracy: 0.7284467816352844, Loss: 0.6590508818626404
Epoch: 72, Accuracy: 0.7239092588424683, Loss: 0.6581319570541382
Epoch: 73, Accuracy: 0.7354275584220886, Loss: 0.6566106081008911
Epoch: 74, Accuracy: 0.7225130796432495, Loss: 0.6592504978179932
Epoch: 75, Accuracy: 0.7403141260147095, Loss: 0.6451836824417114
Epoch: 76, Accuracy: 0.7350785136222839, Loss: 0.6468247771263123
Epoch: 77, Accuracy: 0.753926694393158, Loss: 0.6324202418327332
Epoch: 78, Accuracy: 0.7493891716003418, Loss: 0.6277148723602295
Epoch: 79, Accuracy: 0.7354275584220886, Loss: 0.632731020450592
Epoch: 80, Accuracy: 0.744502604007721, Loss: 0.627234160900116
Epoch: 81, Accuracy: 0.7521815299987793, Loss: 0.6087329983711243
Epoch: 82, Accuracy: 0.7710296511650085, Loss: 0.594031810760498
Epoch: 83, Accuracy: 0.7731239199638367, Loss: 0.586836576461792
Epoch: 84, Accuracy: 0.7713786959648132, Loss: 0.5971636772155762
Epoch: 85, Accuracy: 0.7780104875564575, Loss: 0.5945526957511902
Epoch: 86, Accuracy: 0.764397919178009, Loss: 0.595244824886322
Epoch: 87, Accuracy: 0.7776614427566528, Loss: 0.5807980895042419
Epoch: 88, Accuracy: 0.7664921283721924, Loss: 0.5771047472953796
Epoch: 89, Accuracy: 0.7898778319358826, Loss: 0.5635368227958679
Epoch: 90, Accuracy: 0.7808027863502502, Loss: 0.5658066272735596
Epoch: 91, Accuracy: 0.7842931747436523, Loss: 0.561314046382904
Epoch: 92, Accuracy: 0.7919721007347107, Loss: 0.5533581972122192
Epoch: 93, Accuracy: 0.791623055934906, Loss: 0.5556198954582214
Epoch: 94, Accuracy: 0.7961605787277222, Loss: 0.5601996183395386
Epoch: 95, Accuracy: 0.8038394451141357, Loss: 0.5436417460441589
Epoch: 96, Accuracy: 0.7986038327217102, Loss: 0.5479528903961182
Epoch: 97, Accuracy: 0.8122164011001587, Loss: 0.5264554023742676
Epoch: 98, Accuracy: 0.8219895362854004, Loss: 0.5330337882041931
Epoch: 99, Accuracy: 0.8247818350791931, Loss: 0.514620840549469
Epoch: 100, Accuracy: 0.8146597146987915, Loss: 0.519780158996582
Epoch: 101, Accuracy: 0.829668402671814, Loss: 0.5126711130142212
Epoch: 102, Accuracy: 0.8429319262504578, Loss: 0.4980839490890503
Epoch: 103, Accuracy: 0.8289703130722046, Loss: 0.5008324384689331
Epoch: 104, Accuracy: 0.8520069718360901, Loss: 0.493329793214798
Epoch: 105, Accuracy: 0.8537521958351135, Loss: 0.48559918999671936
Epoch: 106, Accuracy: 0.8492146730422974, Loss: 0.4860363006591797
Epoch: 107, Accuracy: 0.8537521958351135, Loss: 0.47753459215164185
Epoch: 108, Accuracy: 0.8631762862205505, Loss: 0.47241073846817017
Epoch: 109, Accuracy: 0.855497419834137, Loss: 0.45654070377349854
Epoch: 110, Accuracy: 0.8593368530273438, Loss: 0.4562108516693115
Epoch: 111, Accuracy: 0.8722513318061829, Loss: 0.444368839263916
Epoch: 112, Accuracy: 0.875741720199585, Loss: 0.42963582277297974
Epoch: 113, Accuracy: 0.8799301981925964, Loss: 0.43047869205474854
Epoch: 114, Accuracy: 0.8837696313858032, Loss: 0.421707421541214
Epoch: 115, Accuracy: 0.8848167657852173, Loss: 0.4205080568790436
Epoch: 116, Accuracy: 0.8865619897842407, Loss: 0.40574386715888977
Epoch: 117, Accuracy: 0.8890052437782288, Loss: 0.4101424813270569
Epoch: 118, Accuracy: 0.8900523781776428, Loss: 0.38921064138412476
Epoch: 119, Accuracy: 0.8942408561706543, Loss: 0.39366525411605835
Epoch: 120, Accuracy: 0.9005235433578491, Loss: 0.38443800806999207
Epoch: 121, Accuracy: 0.8991274237632751, Loss: 0.37966978549957275
Epoch: 122, Accuracy: 0.9015706777572632, Loss: 0.3872286379337311
Epoch: 123, Accuracy: 0.9106457233428955, Loss: 0.3635827302932739
Epoch: 124, Accuracy: 0.9109947681427002, Loss: 0.3631094694137573
Epoch: 125, Accuracy: 0.9144851565361023, Loss: 0.34895357489585876
Epoch: 126, Accuracy: 0.9082024693489075, Loss: 0.3512488305568695
Epoch: 127, Accuracy: 0.9165794253349304, Loss: 0.3486793041229248
Epoch: 128, Accuracy: 0.9179756045341492, Loss: 0.3389279544353485
Epoch: 129, Accuracy: 0.9186736345291138, Loss: 0.34543347358703613
Epoch: 130, Accuracy: 0.9249563813209534, Loss: 0.33138564229011536
Epoch: 131, Accuracy: 0.9183245897293091, Loss: 0.3331267833709717
Epoch: 132, Accuracy: 0.9172775149345398, Loss: 0.31946879625320435
Epoch: 133, Accuracy: 0.9267016053199768, Loss: 0.3113950788974762
Epoch: 134, Accuracy: 0.9284467697143555, Loss: 0.30850204825401306
Epoch: 135, Accuracy: 0.9315881133079529, Loss: 0.29594656825065613
Epoch: 136, Accuracy: 0.9284467697143555, Loss: 0.3062450587749481
Epoch: 137, Accuracy: 0.9294939041137695, Loss: 0.30152401328086853
Epoch: 138, Accuracy: 0.9343804717063904, Loss: 0.2770349681377411
Epoch: 139, Accuracy: 0.9354276061058044, Loss: 0.27829575538635254
Epoch: 140, Accuracy: 0.9347295165061951, Loss: 0.27540090680122375
Epoch: 141, Accuracy: 0.9389179944992065, Loss: 0.27680104970932007
Epoch: 142, Accuracy: 0.9305410385131836, Loss: 0.28082510828971863
Epoch: 143, Accuracy: 0.936125636100769, Loss: 0.2617625594139099
Epoch: 144, Accuracy: 0.9399651288986206, Loss: 0.26432815194129944
Epoch: 145, Accuracy: 0.9434555172920227, Loss: 0.2596640884876251
Epoch: 146, Accuracy: 0.9445026516914368, Loss: 0.2700944244861603
Epoch: 147, Accuracy: 0.9350785613059998, Loss: 0.25409168004989624
Epoch: 148, Accuracy: 0.9434555172920227, Loss: 0.2621082663536072
Epoch: 149, Accuracy: 0.9410122036933899, Loss: 0.2435678094625473
Epoch: 150, Accuracy: 0.9364746809005737, Loss: 0.26242560148239136
Epoch: 151, Accuracy: 0.9438045620918274, Loss: 0.23728273808956146
Epoch: 152, Accuracy: 0.945549726486206, Loss: 0.2369505614042282
Epoch: 153, Accuracy: 0.9427574276924133, Loss: 0.24055719375610352
Epoch: 154, Accuracy: 0.943106472492218, Loss: 0.2429414540529251
Epoch: 155, Accuracy: 0.9483420848846436, Loss: 0.22862431406974792
Epoch: 156, Accuracy: 0.9476439952850342, Loss: 0.23177464306354523
Epoch: 157, Accuracy: 0.945549726486206, Loss: 0.231105774641037
Epoch: 158, Accuracy: 0.9511343836784363, Loss: 0.22942018508911133
Epoch: 159, Accuracy: 0.943106472492218, Loss: 0.23497772216796875
Epoch: 160, Accuracy: 0.9469459056854248, Loss: 0.22243520617485046
Epoch: 161, Accuracy: 0.9518324732780457, Loss: 0.22651590406894684
Epoch: 162, Accuracy: 0.9535776972770691, Loss: 0.21841533482074738
Epoch: 163, Accuracy: 0.9546247720718384, Loss: 0.21825198829174042
Epoch: 164, Accuracy: 0.9556719064712524, Loss: 0.2151995450258255
Epoch: 165, Accuracy: 0.9535776972770691, Loss: 0.2135896235704422
Epoch: 166, Accuracy: 0.951483428478241, Loss: 0.20903900265693665
Epoch: 167, Accuracy: 0.951483428478241, Loss: 0.2087395340204239
Epoch: 168, Accuracy: 0.9591622948646545, Loss: 0.1966746747493744
Epoch: 169, Accuracy: 0.9581152200698853, Loss: 0.20457032322883606
Epoch: 170, Accuracy: 0.952530562877655, Loss: 0.20572461187839508
Epoch: 171, Accuracy: 0.9570680856704712, Loss: 0.19545237720012665
Epoch: 172, Accuracy: 0.9535776972770691, Loss: 0.1997104436159134
Epoch: 173, Accuracy: 0.9563699960708618, Loss: 0.19714340567588806
Epoch: 174, Accuracy: 0.9549738168716431, Loss: 0.19197778403759003
Epoch: 175, Accuracy: 0.9553228616714478, Loss: 0.20174844563007355
Epoch: 176, Accuracy: 0.9556719064712524, Loss: 0.19737838208675385
Epoch: 177, Accuracy: 0.9546247720718384, Loss: 0.18738695979118347
Epoch: 178, Accuracy: 0.9528796076774597, Loss: 0.1961037665605545
Epoch: 179, Accuracy: 0.9532286524772644, Loss: 0.18355746567249298
Epoch: 180, Accuracy: 0.9563699960708618, Loss: 0.19157861173152924
Epoch: 181, Accuracy: 0.9553228616714478, Loss: 0.1832181215286255
Epoch: 182, Accuracy: 0.9623036980628967, Loss: 0.1835738569498062
Epoch: 183, Accuracy: 0.9612565636634827, Loss: 0.18338286876678467
Epoch: 184, Accuracy: 0.9588132500648499, Loss: 0.17448273301124573
Epoch: 185, Accuracy: 0.9563699960708618, Loss: 0.19146732985973358
Epoch: 186, Accuracy: 0.9598603844642639, Loss: 0.18276475369930267
Epoch: 187, Accuracy: 0.9560209512710571, Loss: 0.18808521330356598
Epoch: 188, Accuracy: 0.9584642052650452, Loss: 0.17625172436237335
Epoch: 189, Accuracy: 0.961954653263092, Loss: 0.17525556683540344
Epoch: 190, Accuracy: 0.9626527428627014, Loss: 0.17459557950496674
Epoch: 191, Accuracy: 0.9602094292640686, Loss: 0.17454534769058228
Epoch: 192, Accuracy: 0.9581152200698853, Loss: 0.1750299632549286
Epoch: 193, Accuracy: 0.9595113396644592, Loss: 0.17747819423675537
Epoch: 194, Accuracy: 0.9602094292640686, Loss: 0.17011259496212006
Epoch: 195, Accuracy: 0.9630017280578613, Loss: 0.17519669234752655
Epoch: 196, Accuracy: 0.9647469520568848, Loss: 0.16360116004943848
Epoch: 197, Accuracy: 0.9605584740638733, Loss: 0.16452106833457947
Epoch: 198, Accuracy: 0.9643979072570801, Loss: 0.1618451178073883
Epoch: 199, Accuracy: 0.9591622948646545, Loss: 0.1706668585538864
Epoch: 200, Accuracy: 0.9623036980628967, Loss: 0.1669928878545761
Epoch: 201, Accuracy: 0.9616056084632874, Loss: 0.15833055973052979
Epoch: 202, Accuracy: 0.961954653263092, Loss: 0.16628000140190125
Epoch: 203, Accuracy: 0.9636998176574707, Loss: 0.15735489130020142
Epoch: 204, Accuracy: 0.960907518863678, Loss: 0.16371425986289978
Epoch: 205, Accuracy: 0.9623036980628967, Loss: 0.16387984156608582
Epoch: 206, Accuracy: 0.9588132500648499, Loss: 0.17755642533302307
Epoch: 207, Accuracy: 0.9630017280578613, Loss: 0.1591423600912094
Epoch: 208, Accuracy: 0.963350772857666, Loss: 0.15826085209846497
Epoch: 209, Accuracy: 0.9636998176574707, Loss: 0.1539537012577057
Epoch: 210, Accuracy: 0.9647469520568848, Loss: 0.15694841742515564
Epoch: 211, Accuracy: 0.9657940864562988, Loss: 0.1580907255411148
Epoch: 212, Accuracy: 0.961954653263092, Loss: 0.160793736577034
Epoch: 213, Accuracy: 0.9643979072570801, Loss: 0.15476660430431366
Epoch: 214, Accuracy: 0.9640488624572754, Loss: 0.15324823558330536
Epoch: 215, Accuracy: 0.9630017280578613, Loss: 0.14905762672424316
Epoch: 216, Accuracy: 0.9647469520568848, Loss: 0.1494857221841812
Epoch: 217, Accuracy: 0.9657940864562988, Loss: 0.15372948348522186
Epoch: 218, Accuracy: 0.9650959968566895, Loss: 0.1541372537612915
Epoch: 219, Accuracy: 0.9664921760559082, Loss: 0.14911675453186035
Epoch: 220, Accuracy: 0.9654450416564941, Loss: 0.14507685601711273
Epoch: 221, Accuracy: 0.9657940864562988, Loss: 0.14527563750743866
Epoch: 222, Accuracy: 0.9654450416564941, Loss: 0.1468028724193573
Epoch: 223, Accuracy: 0.9668412208557129, Loss: 0.152208149433136
Epoch: 224, Accuracy: 0.9678882956504822, Loss: 0.1424601823091507
Epoch: 225, Accuracy: 0.9650959968566895, Loss: 0.14704883098602295
Epoch: 226, Accuracy: 0.9636998176574707, Loss: 0.1513206660747528
Epoch: 227, Accuracy: 0.9664921760559082, Loss: 0.14523160457611084
Epoch: 228, Accuracy: 0.9657940864562988, Loss: 0.13965897262096405
Epoch: 229, Accuracy: 0.9696335196495056, Loss: 0.13704262673854828
Epoch: 230, Accuracy: 0.9664921760559082, Loss: 0.15063953399658203
Epoch: 231, Accuracy: 0.9692844748497009, Loss: 0.13102462887763977
Epoch: 232, Accuracy: 0.971727728843689, Loss: 0.13178153336048126
Epoch: 233, Accuracy: 0.9657940864562988, Loss: 0.13645288348197937
Epoch: 234, Accuracy: 0.9675392508506775, Loss: 0.13873539865016937
Epoch: 235, Accuracy: 0.9664921760559082, Loss: 0.14810673892498016
Epoch: 236, Accuracy: 0.9689354300498962, Loss: 0.14052501320838928
Epoch: 237, Accuracy: 0.9668412208557129, Loss: 0.1343451887369156
Epoch: 238, Accuracy: 0.9668412208557129, Loss: 0.14081870019435883
Epoch: 239, Accuracy: 0.9692844748497009, Loss: 0.13353851437568665
Epoch: 240, Accuracy: 0.9689354300498962, Loss: 0.13677828013896942
Epoch: 241, Accuracy: 0.970331609249115, Loss: 0.1245763972401619
Epoch: 242, Accuracy: 0.9696335196495056, Loss: 0.13386012613773346
Epoch: 243, Accuracy: 0.9699825644493103, Loss: 0.1307046115398407
Epoch: 244, Accuracy: 0.9710296988487244, Loss: 0.12129845470190048
Epoch: 245, Accuracy: 0.9692844748497009, Loss: 0.13063251972198486
Epoch: 246, Accuracy: 0.9710296988487244, Loss: 0.13228200376033783
Epoch: 247, Accuracy: 0.971378743648529, Loss: 0.12632089853286743
Epoch: 248, Accuracy: 0.9706806540489197, Loss: 0.12790825963020325
Epoch: 249, Accuracy: 0.972774863243103, Loss: 0.12280615419149399
Epoch: 250, Accuracy: 0.9696335196495056, Loss: 0.12047335505485535
Epoch: 251, Accuracy: 0.970331609249115, Loss: 0.1287853866815567
Epoch: 252, Accuracy: 0.9710296988487244, Loss: 0.12825946509838104
Epoch: 253, Accuracy: 0.971727728843689, Loss: 0.12769027054309845
Epoch: 254, Accuracy: 0.971727728843689, Loss: 0.12318314611911774
Epoch: 255, Accuracy: 0.9699825644493103, Loss: 0.1277248114347458
Epoch: 256, Accuracy: 0.9706806540489197, Loss: 0.12709476053714752
Epoch: 257, Accuracy: 0.9738219976425171, Loss: 0.1169402077794075
Epoch: 258, Accuracy: 0.9734729528427124, Loss: 0.11862536519765854
Epoch: 259, Accuracy: 0.9748691320419312, Loss: 0.1178903728723526
Epoch: 260, Accuracy: 0.9734729528427124, Loss: 0.12304345518350601
Epoch: 261, Accuracy: 0.972774863243103, Loss: 0.11950524151325226
Epoch: 262, Accuracy: 0.9720767736434937, Loss: 0.11434732377529144
Epoch: 263, Accuracy: 0.9710296988487244, Loss: 0.12250323593616486
Epoch: 264, Accuracy: 0.971378743648529, Loss: 0.12385238707065582
Epoch: 265, Accuracy: 0.9731239080429077, Loss: 0.11634533107280731
Epoch: 266, Accuracy: 0.9745200872421265, Loss: 0.11294599622488022
Epoch: 267, Accuracy: 0.9706806540489197, Loss: 0.12287478148937225
Epoch: 268, Accuracy: 0.9699825644493103, Loss: 0.1109609454870224
Epoch: 269, Accuracy: 0.9748691320419312, Loss: 0.10824865847826004
Epoch: 270, Accuracy: 0.9769633412361145, Loss: 0.10830982774496078
Epoch: 271, Accuracy: 0.9741710424423218, Loss: 0.1077539324760437
Epoch: 272, Accuracy: 0.9738219976425171, Loss: 0.12124088406562805
Epoch: 273, Accuracy: 0.9738219976425171, Loss: 0.11367347091436386
Epoch: 274, Accuracy: 0.9678882956504822, Loss: 0.12267151474952698
Epoch: 275, Accuracy: 0.9745200872421265, Loss: 0.11351484805345535
Epoch: 276, Accuracy: 0.9762652516365051, Loss: 0.10626357048749924
Epoch: 277, Accuracy: 0.9706806540489197, Loss: 0.11328291893005371
Epoch: 278, Accuracy: 0.9734729528427124, Loss: 0.11696842312812805
Epoch: 279, Accuracy: 0.9724258184432983, Loss: 0.11172489821910858
Epoch: 280, Accuracy: 0.9773123860359192, Loss: 0.11528189480304718
Epoch: 281, Accuracy: 0.9720767736434937, Loss: 0.11681291460990906
Epoch: 282, Accuracy: 0.9748691320419312, Loss: 0.10932423174381256
Epoch: 283, Accuracy: 0.9720767736434937, Loss: 0.11159070581197739
Epoch: 284, Accuracy: 0.9752181768417358, Loss: 0.11085620522499084
Epoch: 285, Accuracy: 0.9734729528427124, Loss: 0.10519121587276459
Epoch: 286, Accuracy: 0.9759162664413452, Loss: 0.1133342832326889
Epoch: 287, Accuracy: 0.9759162664413452, Loss: 0.11009378731250763
Epoch: 288, Accuracy: 0.9748691320419312, Loss: 0.10315573215484619
Epoch: 289, Accuracy: 0.9745200872421265, Loss: 0.1096833273768425
Epoch: 290, Accuracy: 0.9734729528427124, Loss: 0.10739805549383163
Epoch: 291, Accuracy: 0.9769633412361145, Loss: 0.0990000069141388
Epoch: 292, Accuracy: 0.9755672216415405, Loss: 0.10171922296285629
Epoch: 293, Accuracy: 0.9745200872421265, Loss: 0.1062583401799202
Epoch: 294, Accuracy: 0.9745200872421265, Loss: 0.10323390364646912
Epoch: 295, Accuracy: 0.9759162664413452, Loss: 0.10244529694318771
Epoch: 296, Accuracy: 0.9759162664413452, Loss: 0.09902405738830566
Epoch: 297, Accuracy: 0.9769633412361145, Loss: 0.10090652853250504
Epoch: 298, Accuracy: 0.9773123860359192, Loss: 0.10093262046575546